# this comment has no meaning 
name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl

    steps:
      - uses: actions/checkout@v4

      - name: Download Kaizen 0.1.0
        shell: bash
        run: |
          mkdir -p "${{ github.workspace }}/external"
          curl -L -o "${{ github.workspace }}/external/kaizen.h" \
               "https://github.com/heinsaar/kaizen/releases/download/0.1.0/kaizen.h"

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Configure CMake
        shell: bash
        run: |
          echo "Configuring CMake..."
          cmake -B "${{ steps.strings.outputs.build-output-dir }}" \
                -S "${{ github.workspace }}" \
                -DCMAKE_CXX_COMPILER="${{ matrix.cpp_compiler }}" \
                -DCMAKE_C_COMPILER="${{ matrix.c_compiler }}" \
                -DCMAKE_BUILD_TYPE="${{ matrix.build_type }}" \
                -DCMAKE_CXX_FLAGS="-I${{ github.workspace }}/external"

      - name: Build
        shell: bash
        run: |
          echo "Building..."
          cmake --build "${{ steps.strings.outputs.build-output-dir }}" --config "${{ matrix.build_type }}"

      - name: Test
        shell: bash
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        run: |
          echo "Running tests..."
          ctest --build-config "${{ matrix.build_type }}"

       - name: Run Executable
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        shell: bash
        run: |
          # Set executable name based on OS
          executable="matrix_benchmark"  # Start with base executable name
          
          if [ "$RUNNER_OS" == "Windows" ]; then
            executable="matrix_benchmark.exe"  # Add .exe for Windows
            # On Windows, we should ensure that we run in the correct directory
            executable_path="${{ github.workspace }}\\build\\${{ matrix.build_type }}\\$executable"  # Absolute path for Windows
          else
            executable_path="${{ github.workspace }}/build/$executable"  # Absolute path for Linux/macOS
          fi
          
          # Check if the file exists before trying to run it
          echo "Checking if executable exists: $executable_path"
          if [ -f "$executable_path" ]; then
            echo "Executable found, running it"
            # Run executable based on the platform
            if [ "$RUNNER_OS" == "Windows" ]; then
              # For Windows, use cmd to run the exe if it's Windows
              "$executable_path" --size 1000 --iterations 300
            else
              # Run directly on Linux/macOS without './' for absolute path
              "$executable_path" --size 1000 --iterations 300  # This works for both Linux/macOS
            fi
          else
            echo "Executable not found: $executable_path"
            exit 1  # Fail if the executable isn't found
          fi